# Generated by Django 6.0.3 on 2026-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', 'XXXX_add_tarifa_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='descuento_sena',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='descuento_trabajador',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
