# Generated by Django 6.0.3 on 2026-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_tarifa_descuento_sena_tarifa_descuento_trabajador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('REGULAR', 'Cliente Regular'), ('SENA', 'Aprendiz SENA'), ('TRABAJADOR', 'Trabajador')], default='REGULAR', max_length=20),
        ),
    ]
