# Generated by Django 6.0.3 on 2026-04-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_client_client_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-entry_time']},
        ),
    ]
