# Generated by Django 6.0.3 on 2026-03-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_parkingspot_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Carro'), ('MOTORCYCLE', 'Moto'), ('BICYCLE', 'Bicicleta')], max_length=20, unique=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_rate',
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.appuser'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='parkingspot',
            table='parking_spot',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.ticket')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
